### PR TITLE
Todo frontend

### PR DESCRIPTION
**Pull request by IngemarWatt**
**Issue:**
#54 Progress on frontend of todo list

**Solution:**
Added end time and end date to todo tasks

**Test Method:** 
Added tests for end time and end date, also fixed existing tests

**Risk:**
No major risks

**Reviewed By:**
[Edit the message as to who reviewed it here]

### CODE REVIEW

**Review by YungiKim1999 — APPROVED** [review]
LGTM

**Review by lucas2005gao — APPROVED** [review]
Cool stuff! Great that you were able to discuss with the team and fix any remaining issues. Great work.

**Review by jzen349 — APPROVED** [review]
Nice changes! LGTM :)

**Comment by IngemarWatt** [comment]
Thanks to @Angstylemon for helping me. The component width fix was very much appreciated.

**Comment by lucas2005gao** [comment]
Would be good to update your contributions in the Wiki, and attach new screenshots into the documentation! Great work @IngemarWatt and thanks @Angstylemon

**Pull request merged**
