### PR TITLE
Upload markdown files for issue templates

### PR DESCRIPTION
**Pull request by Denijar**
**Issue:**
No issues templates have been included in the repository. This will lead to inconsistent issue formats and reduce the readability of the open source project.

**Solution:**
Create default templates for different types of issues.

**Risk:**
N/A

**Reviewed By:**
[Edit the message as to who reviewed it here]

### CODE REVIEW

**Review by kcho9906 — APPROVED** [review]
Nice - how do we choose which template to use when creating?

**Comment by Denijar** [comment]
> 
> 
> Nice - how do we choose which template to use when creating?

I don't know yet unfortunately haha. Once these templates have been merged in I will figure that out (which it seems I must do first according to this guide: https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository) and update the "Issues" documentation accordingly.

**Review by sannan06 — APPROVED** [review]

**Comment by raymondhonsumchiu** [comment]
I think there's a misspelling of enhancement as "enchancement" in the filename enchancement.md and on line 2.

**Comment by Denijar** [comment]
@raymondhonsumchiu thanks for that pick up - I have fixed it.
I am going to close this PR. Please refer to #33

**Pull request closed without merging**
