### PR TITLE
Server readme

### PR DESCRIPTION
**Pull request by Jennak21**
Issue:
#24 README.md for backend

Solution:
Created a README.md that included the installation, usage, testing, and contributing.

Test Method:
N/A

Risk:
N/A

Reviewed By:
Raymond

### CODE REVIEW

**Review by raymondhonsumchiu — APPROVED** [review]
Looks good!

**Comment by vkoil** [comment]
Should we consider adding the links to the documentation for Firebase, Jest, etc.?
I understand how in this case, since both frameworks are quite popular, we don't necessarily need it, however when dealing with more obscure frameworks or libraries, it would become really useful.

**Comment by Jennak21** [comment]
> Should we consider adding the links to the documentation for Firebase, Jest, etc.?
> I understand how in this case, since both frameworks are quite popular, we don't necessarily need it, however when dealing with more obscure frameworks or libraries, it would become really useful.

Good point and I was considering that also. However, after reading the comments left on this PR (https://github.com/SE701Group2/daily-focus/pull/99), it seems like a readme should not be a repetition of the wiki. In the wiki, I have put links to documentation.

**Review by Denijar — APPROVED** [review]
Nice readme. Thanks for editing the top level README :)))

**Pull request merged**
