### PR TITLE
Upload markdown file for pull request template

### PR DESCRIPTION
**Pull request by kcho9906**
**Issue:**
No pull request templates have been included in the repository. This will lead to inconsistent pull request formats and reduce the readability of the open source project.

**Solution:**
Create a markdown file and upload the pull request template

**Test Method:** 
No testing required for setup

**Risk:**
N/A

**Reviewed By:**
@dikunong @sannan06

### CODE REVIEW

**Comment by dikunong** [comment]
Looks good! I would suggest adding a section specifically for linking the GitHub issue (e.g. #23) to ensure people don't forget.

**Comment by kcho9906** [comment]
> Looks good! I would suggest adding a section specifically for linking the GitHub issue (e.g. #23) to ensure people don't forget.
> 
> e.g.
> **Linked GitHub issue:**
> #23

Hmmmm, this is done in the right hand side of a pull request though - the pull request template just presets the message of the pull request. 

Screenshot 2021-03-12 183306

**Comment by dikunong** [comment]
> Hmmmm, this is done in the right hand side of a pull request though - the pull request template just presets the message of the pull request.

Ah yeah true, that's fair. We should definitely mention it in the contributing guidelines - the main thing is just making sure people remember to do it.

**Review by dikunong — APPROVED** [review]
Good work!

**Comment by sannan06** [comment]
Do you guys see any value in adding a "Test Method" section so you can get clarity/traceability on how the solution was tested to be working (e.g. unit test, developer manual etc.)?

**Review by sannan06 — APPROVED** [review]

**Pull request merged**
