### PR TITLE
Signup API handler

### LINKED ISSUE #44: Create sign-up API handler
**User Story**
As a user, I want to be able to sign-up for an account

**Acceptance Criteria**
- User account should be managed by Firebase Authentication
- User account should be created with an email address and password
- Email should be checked that it is in a valid format

### PR DESCRIPTION
**Pull request by Jennak21**
**Issue:**
resolves #44 

**Solution:**
A function was created which will be invoked at the "/login" endpoint. This function first creates a user in firebase authentication, creates a user object in the firebase database with the generated user id, and returns a response with the token.

**Test Method:** 
Manually tested using postman
and unit testing using Jest

**Risk:**

**Reviewed By:**

### CODE REVIEW

**Review by Pranavan10 — APPROVED** [review]
Looks good 👍

**Comment by raymondhonsumchiu** [comment]
Would it be possible to initialise an empty todolist array when creating a new user?

**Comment by Jennak21** [comment]
> Would it be possible to initialise an empty todolist array when creating a new user?

I tried that but it didn't work, I'll try again though

**Comment by Jennak21** [comment]
> Would it be possible to initialise an empty todolist array when creating a new user?
I tried this
```
            const user = {
                email: newUser.email,
                todolist: {}
            };
```
and since the object is empty it doesn't show up on the database

also I just saw this https://firebase.googleblog.com/2014/04/best-practices-arrays-in-firebase.html?fbclid=IwAR1qDSaglUl8_qMJiXfdKj8sPdT3sC-fbzz8z8SCrMIBJvwT_g7gpKTOUho which explains that we shouldn't be using arrays

**Comment by raymondhonsumchiu** [comment]
Hmm do we have to remove our arrays and use the method used in that link?

**Review by Pranavan10 — APPROVED** [review]

**Review by raymondhonsumchiu — APPROVED** [review]
Got the listening on port 3000 there, but I will remove it in another PR

**Pull request merged**
