### PR TITLE
Todolist PUT Endpoint

### PR DESCRIPTION
**Pull request by vkoil**
**Issue:**
Needed a way to update ToDoList
Resolves Issue #40 
 
**Solution:**
Implemented PUT API endpoint which updates firebase database.

**Test Method:** 
Added unit tests in the putTodo.test.js using Jest using the mock database .
Followed up with manual testing through Postman.

**Risk:**
No data validation in current implementation.

**Reviewed By:**
Pranavan10, raymondhonsumchiu, jshi213

### CODE REVIEW

**Review by raymondhonsumchiu — APPROVED** [review]
Looks good to me

**Review by jshi213 — APPROVED** [review]
LGTM

**Review by jshi213 — CHANGES_REQUESTED** [review]
expectedToDoListData in putTodo.test.js will have to be changed so it corresponds to new data in mockDatabase

**Comment by raymondhonsumchiu** [comment]
Seems there's a conflict due to a new change in main, might need to rebase?

**Review by Pranavan10 — APPROVED** [review]

**Review by vkoil — COMMENTED** [review]
Matches new database now.

**Comment by vkoil** [comment]
> expectedToDoListData in putTodo.test.js will have to be changed so it corresponds to new data in mockDatabase which includes today's date

Completed the update and tested it as well.

**Review by jshi213 — APPROVED** [review]
LGTM

**Pull request merged**
